name: CI/CD Backend HIE to AWS EC2

on:
  push:
    branches: [ deploy ]

jobs:
  # 1. Job: Checkout, Build Docker image và Push Docker image lên Docker Hub
  build_image_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nestjs-hie:latest

  # 2. Job: Deploy lên EC2
  deploy_ec2:
    runs-on: ubuntu-latest
    needs: build_image_and_push_image
    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pull image mới nhất
            docker pull ${{ secrets.DOCKER_USERNAME }}/nestjs-hie:latest

            # Xóa mọi container đang dùng port 3555
            docker ps -q --filter "publish=3555" | xargs -r docker stop
            docker ps -aq --filter "publish=3555" | xargs -r docker rm
            
            # Xóa container cũ (dù đã stop)
            docker rm -f nestjs-hie || true


            # Chạy container mới
            docker run -d -p 3555:3000 \
              --name nestjs-hie \
              --env=DB_HOST=${{ secrets.DB_HOST }} \
              --env=DB_PORT=3306 \
              --env=DB_USERNAME=${{ secrets.DB_USERNAME }} \
              --env=DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
              --env=DB_DATABASE=${{ secrets.DB_DATABASE }} \
              --env=JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
              --env=JWT_EXPIRATION_TIME=2592000 \
              --env=AWS_REGION=${{ secrets.AWS_REGION }} \
              --env=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
              --env=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
              --env=AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }} \
              --env=WALLET_PRIVATE_KEY=${{ secrets.WALLET_PRIVATE_KEY }} \
              --env=CONTRACT_ADDRESS=${{ secrets.CONTRACT_ADDRESS }} \
              --env=RPC_URL=${{ secrets.RPC_URL }} \
              --env=HIS_URL=${{ secrets.HIS_URL }} \
              --env=SOURCE_URL=https://${{ secrets.EC2_HOST }}:3555 \
              --env=ORIGIN_URL=${{ secrets.ORIGIN_URL }} \
              --env=AVAILABLE_METHODS=GET,HEAD,PUT,PATCH,POST,DELETE \
              --network=bridge \
              --restart=no \
              ${{ secrets.DOCKER_USERNAME }}/nestjs-hie:latest

            # Xoá tất cả images ko có container đi kèm
            docker image prune -a -f
